#!/usr/bin/env bash
REPO_DEFAULT_DIR=/opt/fortify-lab-source
repo_require_tools(){ command_exists git || die 'git is required'; command_exists gh || die 'GitHub CLI is required'; }
repo_auth(){ repo_require_tools; gh auth status >/dev/null 2>&1 && ok 'GitHub CLI already authenticated' || gh auth login; }
repo_status(){ repo_require_tools; local d; d=$(config_get REPOSITORY_DIR); d=${d:-$REPO_DEFAULT_DIR}; [[ -d "$d/.git" ]] || die "No Git repository at $d"; git -C "$d" status --short --branch; git -C "$d" remote -v; git -C "$d" rev-parse --short HEAD; }
repo_validate(){ local d=${1:-$(config_get REPOSITORY_DIR)}; d=${d:-$REPO_DEFAULT_DIR}; [[ -d "$d/.git" ]] || die "Not a Git repository: $d"; [[ -x "$d/install.sh" && -x "$d/tests/run-tests.sh" ]] || die 'Repository is not a valid Fortify toolkit repository'; (cd "$d" && ./tests/run-tests.sh); }
repo_clone(){ need_root; repo_require_tools; local u=${1:-} d=${2:-}; [[ -n "$u" ]] || read -rp 'Repository URL or OWNER/REPO: ' u; [[ -n "$d" ]] || { read -rp "Clone destination [$REPO_DEFAULT_DIR]: " d; d=${d:-$REPO_DEFAULT_DIR}; }; [[ ! -e "$d" || -z "$(ls -A "$d" 2>/dev/null)" ]] || die "Destination is not empty: $d"; if [[ "$u" =~ ^https?://|^git@ ]]; then git clone "$u" "$d"; else gh repo clone "$u" "$d"; fi; config_set REPOSITORY_URL "$u"; config_set REPOSITORY_DIR "$d"; repo_validate "$d"; }
repo_update(){ need_root; repo_require_tools; local d old new; d=$(config_get REPOSITORY_DIR); d=${d:-$REPO_DEFAULT_DIR}; [[ -d "$d/.git" ]] || die "No repository at $d"; [[ -z "$(git -C "$d" status --porcelain)" ]] || die 'Repository has local changes'; [[ -n "$(git -C "$d" branch --show-current)" ]] || die 'Detached HEAD'; old=$(git -C "$d" rev-parse HEAD); git -C "$d" fetch --prune --tags; git -C "$d" pull --ff-only; new=$(git -C "$d" rev-parse HEAD); if ! repo_validate "$d"; then git -C "$d" reset --hard "$old"; die 'Update failed tests and was rolled back'; fi; ok "Repository commit ${new:0:12} validated"; confirm 'Install validated update?' && "$d/install.sh"; }
repo_menu(){ while true; do echo '1) Authenticate 2) Clone 3) Status 4) Update and validate 5) Validate 0) Back'; read -rp 'Select: ' n; case $n in 1) repo_auth;;2) repo_clone;;3) repo_status;;4) repo_update;;5) repo_validate;;0) return;;esac; done; }
